#!/bin/bash

brew install bash-completion
brew install macvim --override-system-vim
brew install coreutils
brew install cowsay
brew install dnsmasq
brew install editorconfig
brew install gifsicle
brew install git
brew install git-extras
brew install gnupg
brew install httpie
brew install imagemagick
brew install netcat
brew install nmap
brew install node
brew install openssl
brew install pwgen
brew install redis
brew install rename
brew install tree
brew install wget
