#!/bin/bash

brew install macvim --with-override-system-vim --with-cscope --with-lua
brew install \
  awscli \
  bash-completion \
  coreutils \
  ctags \
  curl \
  direnv \
  dnsmasq \
  editorconfig \
  gifsicle \
  git \
  git-extras \
  gnupg \
  go \
  httpie \
  imagemagick \
  jq \
  most \
  netcat \
  nmap \
  node \
  openssl \
  pwgen \
  python \
  redis \
  rename \
  shellcheck \
  the_silver_searcher \
  tig \
  tree \
  watch \
  wget
